declare const html2pdf: any;

interface EmployerLetterData {
  employeeName: string;
  employeeId?: string;
  companyName: string;
  hrManager?: string;
}

interface LandlordLetterData {
  tenantName: string;
  landlordName: string;
  propertyAddress?: string;
  annualRent?: string;
}

export const generateEmployerLetter = (data: EmployerLetterData) => {
  const currentDate = new Date().toLocaleDateString('en-GB');
  
  const letterHTML = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6;">
      <div style="text-align: center; margin-bottom: 30px;">
        <div style="display: inline-block; width: 60px; height: 60px; background: #008751; border-radius: 8px; color: white; font-size: 32px; font-weight: bold; line-height: 60px; margin-bottom: 10px;">₦</div>
        <h1 style="color: #008751; margin: 0;">NaijaTaxAssist</h1>
        <p style="color: #666; margin: 5px 0 0 0;">Nigeria Tax Reform 2025 Guide</p>
      </div>
      
      <div style="margin-bottom: 30px;">
        <p><strong>Date:</strong> ${currentDate}</p>
        <p><strong>To:</strong> ${data.hrManager || 'HR Manager'}</p>
        <p><strong>Company:</strong> ${data.companyName}</p>
        <p><strong>From:</strong> ${data.employeeName}</p>
        ${data.employeeId ? `<p><strong>Employee ID:</strong> ${data.employeeId}</p>` : ''}
      </div>
      
      <h2 style="color: #008751;">RE: PAYE TAX EXEMPTION NOTIFICATION - NIGERIA TAX REFORM 2025</h2>
      
      <p>Dear ${data.hrManager || 'HR Manager'},</p>
      
      <p>I am writing to formally notify you of my tax exemption status under the new Nigeria Tax Reform Act 2025, which came into effect on January 1, 2025.</p>
      
      <p><strong>Key Information:</strong></p>
      <ul>
        <li>Under the new tax reforms, individuals earning ₦1,000,000 or less annually are exempt from Pay As You Earn (PAYE) tax</li>
        <li>This exemption applies to the total annual gross salary including allowances</li>
        <li>The reform aims to provide relief to low and middle-income earners</li>
      </ul>
      
      <p><strong>Request:</strong></p>
      <p>Based on my current annual salary, I qualify for this exemption. I kindly request that you:</p>
      <ol>
        <li>Update my payroll records to reflect this tax exemption status</li>
        <li>Cease deducting PAYE tax from my salary effective immediately</li>
        <li>Provide written confirmation of this adjustment</li>
      </ol>
      
      <p><strong>Legal Reference:</strong></p>
      <p>This exemption is provided under Section 3 of the Nigeria Tax Reform Act 2025, as published by the Federal Inland Revenue Service (FIRS).</p>
      
      <p>I have attached relevant documentation and am available to discuss this matter further if needed. Thank you for your prompt attention to this matter.</p>
      
      <p>Sincerely,</p>
      <p><strong>${data.employeeName}</strong></p>
      
      <hr style="margin: 30px 0; border: none; border-top: 1px solid #ddd;">
      
      <div style="font-size: 12px; color: #666; text-align: center;">
        <p>This letter was generated by NaijaTaxAssist - Nigeria Tax Reform 2025 Guide</p>
        <p>Built by Abdulrahman Adisa Amuda 🇳🇬</p>
        <p>For more information, visit: https://naijatuaxassist.com</p>
      </div>
    </div>
  `;

  const element = document.createElement('div');
  element.innerHTML = letterHTML;
  
  const opt = {
    margin: 0.5,
    filename: `PAYE_Exemption_Letter_${data.employeeName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
  };

  html2pdf().set(opt).from(element).save();
};

export const generateLandlordLetter = (data: LandlordLetterData) => {
  const currentDate = new Date().toLocaleDateString('en-GB');
  
  const letterHTML = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6;">
      <div style="text-align: center; margin-bottom: 30px;">
        <div style="display: inline-block; width: 60px; height: 60px; background: #008751; border-radius: 8px; color: white; font-size: 32px; font-weight: bold; line-height: 60px; margin-bottom: 10px;">₦</div>
        <h1 style="color: #008751; margin: 0;">NaijaTaxAssist</h1>
        <p style="color: #666; margin: 5px 0 0 0;">Nigeria Tax Reform 2025 Guide</p>
      </div>
      
      <div style="margin-bottom: 30px;">
        <p><strong>Date:</strong> ${currentDate}</p>
        <p><strong>To:</strong> ${data.landlordName}</p>
        ${data.propertyAddress ? `<p><strong>Property:</strong> ${data.propertyAddress}</p>` : ''}
        <p><strong>From:</strong> ${data.tenantName}</p>
      </div>
      
      <h2 style="color: #008751;">RE: STAMP DUTY EXEMPTION NOTIFICATION - NIGERIA TAX REFORM 2025</h2>
      
      <p>Dear ${data.landlordName},</p>
      
      <p>I am writing to inform you about the stamp duty exemption provisions under the new Nigeria Tax Reform Act 2025, which affects our tenancy agreement.</p>
      
      <p><strong>Key Information:</strong></p>
      <ul>
        <li>Under the new tax reforms, tenancy agreements with annual rent of ₦10,000,000 or less are exempt from stamp duty</li>
        <li>This exemption applies to residential property rentals</li>
        <li>The reform aims to reduce the cost of housing for average income earners</li>
      </ul>
      
      ${data.annualRent ? `<p><strong>Current Rental Details:</strong></p>
      <p>Annual Rent: ₦${parseFloat(data.annualRent).toLocaleString()}</p>
      <p>Based on the annual rent amount, this tenancy qualifies for stamp duty exemption.</p>` : ''}
      
      <p><strong>Legal Implication:</strong></p>
      <p>This means that:</p>
      <ol>
        <li>No stamp duty is required to be paid on our tenancy agreement</li>
        <li>The agreement remains legally valid without stamp duty payment</li>
        <li>Both parties benefit from reduced transaction costs</li>
      </ol>
      
      <p><strong>Legal Reference:</strong></p>
      <p>This exemption is provided under Section 5 of the Nigeria Tax Reform Act 2025, as published by the Federal Inland Revenue Service (FIRS).</p>
      
      <p>I wanted to bring this to your attention for your records and future reference. This does not affect any other terms of our tenancy agreement.</p>
      
      <p>Thank you for your understanding.</p>
      
      <p>Sincerely,</p>
      <p><strong>${data.tenantName}</strong></p>
      
      <hr style="margin: 30px 0; border: none; border-top: 1px solid #ddd;">
      
      <div style="font-size: 12px; color: #666; text-align: center;">
        <p>This letter was generated by NaijaTaxAssist - Nigeria Tax Reform 2025 Guide</p>
        <p>Built by Abdulrahman Adisa Amuda 🇳🇬</p>
        <p>For more information, visit: https://naijatuaxassist.com</p>
      </div>
    </div>
  `;

  const element = document.createElement('div');
  element.innerHTML = letterHTML;
  
  const opt = {
    margin: 0.5,
    filename: `Stamp_Duty_Exemption_Letter_${data.tenantName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
  };

  html2pdf().set(opt).from(element).save();
};
