import html2canvas from "html2canvas";
import jsPDF from "jspdf";

interface EmployerLetterData {
  employeeName: string;
  employeeId?: string;
  companyName: string;
  hrManager?: string;
}

interface LandlordLetterData {
  tenantName: string;
  landlordName: string;
  propertyAddress?: string;
  annualRent?: string;
}

const downloadPdf = async (html: string, filename: string) => {
  const container = document.createElement("div");
  container.innerHTML = html;
  container.style.position = "absolute";
  container.style.left = "-9999px";
  container.style.top = "0";
  container.style.background = "#fff";
  container.style.minHeight = "1200px"; // ensures space for footer

  document.body.appendChild(container);

  await new Promise((resolve) => setTimeout(resolve, 100));

  const canvas = await html2canvas(container, { scale: 2 });
  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF("p", "pt", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();
  const imgProps = pdf.getImageProperties(imgData);
  const ratio = imgProps.width / imgProps.height;
  const pdfHeight = pageWidth / ratio;

  pdf.addImage(imgData, "PNG", 0, 0, pageWidth, pdfHeight);
  pdf.save(filename);

  document.body.removeChild(container);
};

export const generateEmployerLetter = (data: EmployerLetterData) => {
  const currentDate = new Date().toLocaleDateString("en-GB");
  const filename = `PAYE_Exemption_Letter_${data.employeeName.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;

  const letterHTML = `
    <div style="font-family: 'Times New Roman', serif; max-width: 800px; margin: 40px auto; padding: 40px; padding-bottom: 100px; min-height: 1200px; line-height: 1.8; color: #000; font-size: 14px; background: #fff;">
      <div style="text-align: center; margin-bottom: 40px; border-bottom: 3px solid #008751; padding-bottom: 20px;">
        <h1 style="color: #008751;">FEDERAL REPUBLIC OF NIGERIA</h1>
        <h2 style="color: #333;">MINISTRY OF FINANCE</h2>
        <p style="color: #666;">Tax Reform Implementation Unit</p>
        <h3 style="color: #008751; margin-top: 20px;">Official Tax Exemption Notification</h3>
      </div>

      <p><strong>Date:</strong> ${currentDate}</p>
      <p><strong>To:</strong> ${data.hrManager || "HR Manager"}</p>
      <p><strong>Company:</strong> ${data.companyName}</p>
      <p><strong>From:</strong> ${data.employeeName}</p>
      ${data.employeeId ? `<p><strong>Employee ID:</strong> ${data.employeeId}</p>` : ""}

      <h3 style="color: #008751;">RE: PAYE TAX EXEMPTION NOTIFICATION - NIGERIA TAX REFORM 2025</h3>

      <p>Dear ${data.hrManager || "HR Manager"},</p>
      <p>I am writing to notify you of my tax exemption status under the Nigeria Tax Reform Act 2025.</p>

      <ul>
        <li>Individuals earning ₦1,000,000 or less annually are exempt from PAYE tax.</li>
        <li>This applies to gross salary including allowances.</li>
        <li>Intended to support low and middle-income earners.</li>
      </ul>

      <p><strong>Request:</strong></p>
      <ol>
        <li>Update payroll records to reflect tax exemption.</li>
        <li>Cease PAYE tax deductions immediately.</li>
        <li>Provide written confirmation of this change.</li>
      </ol>

      <div style="border-left: 4px solid #008751; padding-left: 10px; background: #f8f9fa;">
        <p><strong>Legal Reference:</strong></p>
        <p>This exemption is provided under Section 3 of the Nigeria Tax Reform Act 2025 by the FIRS.</p>
      </div>

      <p>Thank you for your prompt attention to this matter.</p>

      <p style="margin-top: 40px;">Yours faithfully,</p>
      <p style="margin-top: 30px;"><strong>${data.employeeName}</strong><br>Employee</p>

      <div style="font-size: 10px; text-align: center; margin-top: 60px; border-top: 1px solid #ccc; padding-top: 10px;">
        Generated by <strong>NaijaTaxAssist</strong><br>
        Developed by <strong>Abdulrahman Adisa Amuda 🇳🇬</strong><br>
        <a href="https://www.naijataxassist.com" style="color:#008751;">www.naijataxassist.com</a><br>
        <em>"Making Tax Reforms Accessible to Every Nigerian"</em>
      </div>
    </div>
  `;

  downloadPdf(letterHTML, filename);
};

export const generateLandlordLetter = (data: LandlordLetterData) => {
  const currentDate = new Date().toLocaleDateString("en-GB");
  const filename = `Stamp_Duty_Exemption_Letter_${data.tenantName.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;

  const letterHTML = `
    <div style="font-family: 'Times New Roman', serif; max-width: 800px; margin: 40px auto; padding: 40px; line-height: 1.8; color: #000; font-size: 14px; background: #fff;">
      <div style="text-align: center; margin-bottom: 40px; border-bottom: 3px solid #008751; padding-bottom: 20px;">
        <h1 style="color: #008751;">FEDERAL REPUBLIC OF NIGERIA</h1>
        <h2 style="color: #333;">MINISTRY OF FINANCE</h2>
        <p style="color: #666;">Tax Reform Implementation Unit</p>
        <h3 style="color: #008751; margin-top: 20px;">Stamp Duty Exemption Notification</h3>
      </div>

      <p><strong>Date:</strong> ${currentDate}</p>
      <p><strong>To:</strong> ${data.landlordName}</p>
      <p><strong>From:</strong> ${data.tenantName}</p>
      ${data.propertyAddress ? `<p><strong>Property Address:</strong> ${data.propertyAddress}</p>` : ""}
      ${data.annualRent ? `<p><strong>Annual Rent:</strong> ₦${parseFloat(data.annualRent).toLocaleString()}</p>` : ""}

      <h3 style="color: #008751;">RE: STAMP DUTY EXEMPTION - NIGERIA TAX REFORM 2025</h3>

      <p>Dear ${data.landlordName},</p>
      <p>I am writing to inform you that our tenancy agreement qualifies for stamp duty exemption under the new reform.</p>

      <ul>
        <li>Rent ₦10,000,000 or less annually = Exempt from stamp duty</li>
        <li>Applies to residential properties</li>
        <li>Helps reduce housing costs</li>
      </ul>

      <div style="border-left: 4px solid #008751; padding-left: 10px; background: #f8f9fa;">
        <p><strong>Legal Reference:</strong></p>
        <p>Section 5 of the Nigeria Tax Reform Act 2025 by FIRS</p>
      </div>

      <p>This does not affect other tenancy terms.</p>

      <p style="margin-top: 40px;">Yours respectfully,</p>
      <p style="margin-top: 30px;"><strong>${data.tenantName}</strong><br>Tenant</p>

      <div style="font-size: 10px; text-align: center; margin-top: 60px; border-top: 1px solid #ccc; padding-top: 10px;">
        Generated by <strong>NaijaTaxAssist</strong><br>
        Developed by <strong>Abdulrahman Adisa Amuda 🇳🇬</strong><br>
        <a href="https://www.naijataxassist.com" style="color:#008751;">www.naijataxassist.com</a><br>
        <em>"Making Tax Reforms Accessible to Every Nigerian"</em>
      </div>
    </div>
  `;

  downloadPdf(letterHTML, filename);
};